site_name: Erstsemesterakademie BaW체 zukunftsf채hig - Digitale Umsetzung
site_url: https://help.ersti-akademie-bw.de
repo_url: https://github.com/davidkopp/ersti-akademie-help
nav:
    - Start: index.md
    - BigBlueButton:
        Allgemeines: bbb.md
        Verbindungsaufbau zur Konferenz: bbb-verbindung.md
        Benutzungsoberfl채che: bbb-benutzung.md
    - Matrix:
        Allgemeines: matrix.md
        Registrierung & Anmeldung: matrix-registrierung.md
        Wichtige Einstellungen: matrix-einstellungen.md
        Unsere Community und R채ume: matrix-community.md
        Matrix-Clients: matrix-clients.md
theme:
    name: material
    language: de
    palette:
        primary: green
        accent: green
    features:
      - navigation.tabs
      - toc.autohide
markdown_extensions:
    - admonition
    - pymdownx.critic
    - pymdownx.betterem:
        smart_enable: all
